### PR TITLE
Add Chinese and language options

### PR DESCRIPTION
**Pull request by taskschd1145**
Now when you open it, you will be prompted to choose English or Chinese
image

### CODE REVIEW

**Comment by mowhn** [comment]
> Now when you open it, you will be prompted to choose English or Chinese image

Well thank you 🌟

**Comment by taskschd1145** [comment]
> > Now when you open it, you will be prompted to choose English or Chinese image
> 
> Well thank you 🌟

My pleasure😊

**Comment by mowhn** [comment]
> > > Now when you open it, you will be prompted to choose English or Chinese image
> > 
> > 
> > Well thank you 🌟
> 
> My pleasure😊

Can we work on a project together if you are interested?

**Comment by taskschd1145** [comment]
> > > > Now when you open it, you will be prompted to choose English or Chinese image
> > > 
> > > 
> > > Well thank you 🌟
> > 
> > 
> > My pleasure😊
> 
> Can we work on a project together if you are interested?

What project

**Comment by mowhn** [comment]
> > > > > Now when you open it, you will be prompted to choose English or Chinese image
> > > > 
> > > > 
> > > > Well thank you 🌟
> > > 
> > > 
> > > My pleasure😊
> > 
> > 
> > Can we work on a project together if you are interested?
> 
> What project

Some reverse engineering and Ai project.

**Comment by taskschd1145** [comment]
> > > > > > Now when you open it, you will be prompted to choose English or Chinese image
> > > > > 
> > > > > 
> > > > > Well thank you 🌟
> > > > 
> > > > 
> > > > My pleasure😊
> > > 
> > > 
> > > Can we work on a project together if you are interested?
> > 
> > 
> > What project
> 
> Some reverse engineering and Ai project.

I'm sorry, I can't do that😅
Thank you😊

**Comment by mowhn** [comment]
> > > > > > > Now when you open it, you will be prompted to choose English or Chinese image
> > > > > > 
> > > > > > 
> > > > > > Well thank you 🌟
> > > > > 
> > > > > 
> > > > > My pleasure😊
> > > > 
> > > > 
> > > > Can we work on a project together if you are interested?
> > > 
> > > 
> > > What project
> > 
> > 
> > Some reverse engineering and Ai project.
> 
> I'm sorry, I can't do that😅 Thank you😊

I will email you for details.

**Pull request merged**
